### ISSUE TITLE
use instructions

### ISSUE THREAD

**Issue by storyboat** [cgwire/kitsu-publisher-next#31]
I have installed publisher and connector for blender? where i should look for addon in blender?

**Comment by EvanBldy** [comment]
Hi @storyboat, you should look for addon in "Preferences" --> Add-ons and normally there's a plugin "Import-Export: Kitsu Publisher".

**Comment by storyboat** [comment]
Hi, thanks for reply. Addon is turned on but it seams to not work... Can't find any menu or operator Kitsu related...

**Comment by EvanBldy** [comment]
There's no additional menu in Blender, you have to launch the Kitsu Publisher desktop app select an assigned task to you and when you click on "Add preview to publish" you will now be able to import from Blender :)

**Comment by EvanBldy** [comment]
Hi @storyboat, did you manage to make it work ? :)

**Comment by storyboat** [comment]
> Hi @storyboat, did you manage to make it work ? :)

Hi, yes it works ! Thank you

**Comment by EvanBldy** [comment]
Cool ! Effectively it need more information about how to use it :) 
When I have time I will add some screenshots etc 
If you find some bugs and improvements, don't hesitate to tell us 
Thanks for the report
