### ISSUE TITLE
How to Install and confiigure Kitsu Publisher

### ISSUE THREAD

**Issue by itsupportknack** [cgwire/kitsu-publisher-next#37]
I installed the Kitsu Publisher application in Windows. And i login with user name, Password & Server IP Address. But i am getting the error" The Connection to the server failed, Please verify the address". I installed server in Linux Virtual Machine. Please solve the issue. And how to work with Kitsu Publisher. Orelse i need to install any in server a for Kitsu Publisher

**Comment by frankrousseau** [comment]
Hello, it's probably because you didn't set a propre server address. Are you sure you used the right IP and port to access the server?

**Comment by itsupportknack** [comment]
I used right Ip address with (https://x.x.x.x) what is the port to access it. We followed the kitsu official documents only for installation. If there is any ports pls tell us we check and update u

**Comment by itsupportknack** [comment]
need to install any additional plugins for kitsu publisher in server ?

**Comment by frankrousseau** [comment]
@EvanBldy Can you check what is wrong there?

**Comment by itsupportknack** [comment]
I have installed with package in my server mentioned in your documents. But its not working for kitsu publisher. Please solve the issue.

**Comment by frankrousseau** [comment]
Ping @EvanBldy

**Comment by EvanBldy** [comment]
Hi @itsupportknack 
When do you get the error ? 
When you try to log in ?
Can we get the full stacktrace ? 
You need to open the console in the publisher (with ctrl + shift + i).

**Comment by EvanBldy** [comment]
I think it can be related to the fact that I changed status code for wrong auth to 401

**Comment by itsupportknack** [comment]
[Kitsu_Org.txt](https://github.com/cgwire/kitsu-publisher-next/files/10164025/Kitsu_Org.txt)

As per the details i have taken and attached the stacktrace from the Kitsu Publisher Application. PLease check and solve the issue we are facing

**Comment by itsupportknack** [comment]
In webpage i can able to login. My issue is only with Kitsu Publisher

**Comment by itsupportknack** [comment]
waiting for you reply

**Comment by itsupportknack** [comment]
waiting sir for your reply

**Comment by EvanBldy** [comment]
You need to use http://x.x.x.x (your IP of Kitsu server) not https because it will check for a certificate that your server don't have. 
Please note that you have your login / password / IP in your txt file.

**Comment by itsupportknack** [comment]
I tried with http also Not working in Publisher. Working in Webpage only. Need to mention any port in publisher a???

**Comment by EvanBldy** [comment]
Can you give the stacktrace with http ?

**Comment by itsupportknack** [comment]
[Kitsu_Org2.txt](https://github.com/cgwire/kitsu-publisher-next/files/10185716/Kitsu_Org2.txt)

As per the request i have uploaded pls check and tell the solution

**Comment by EvanBldy** [comment]
You have a connection refused if you go on http://192.168.115.52/api in browser what do you have ?

**Comment by EvanBldy** [comment]
The error is not related to the publisher it's related to your networking configuration. I can't help you here... 
You have to type the address of your Kitsu server (not the API), it's the same address that you use when you go in the login page.

**Comment by itsupportknack** [comment]
or give us any documentations for both Kitsu Server and also for Kitsu Publisher application.

**Comment by frankrousseau** [comment]
Sorry @itsupportknack, we can't help this way. You can take a subscription to our services and we will handle everything for you. All the information are available here: https://cg-wire.com
